# Generated by Django 2.0.5 on 2018-06-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drdiary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='username',
        ),
    ]
