# Generated by Django 2.0.5 on 2018-06-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drdiary', '0006_auto_20180611_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='draft',
        ),
    ]
