# Generated by Django 2.0.5 on 2018-06-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drdiary', '0007_remove_diary_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='updated_at',
        ),
    ]
