# Generated by Django 2.0.5 on 2018-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drdiary', '0009_auto_20180612_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='body',
            field=models.TextField(max_length=10000),
        ),
    ]
