# Generated by Django 2.0.5 on 2018-06-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drdiary', '0010_auto_20180613_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
